---
abstract: 'Bus drivers, Instrument drivers, and measurement scripts'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
  - 'Andreas K. Huettel <mail@akhuettel.de>'
  - 'Daniela Taubert <daniela.taubert@physik.uni-muenchen.de>'
  - 'Florian Olbrich <florian.olbrich@physik.uni-r.de>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Measurement
requires:
  Cwd: 0
  Data::Dumper: 0
  Encode: 0
  Exception::Class: 1.0
  File::Basename: 0
  File::Copy: 0
  File::ShareDir: 1.00
  Term::ReadKey: 0
  Time::HiRes: 0
  XML::DOM: 0
  XML::Generator: 0
  XML::Twig: 0
  encoding::warnings: 0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Measurement
  homepage: http://www.labmeasurement.de/
  license: http://dev.perl.org/licenses/
version: 2.91
