sudo: false

addons:
  apt:
    packages:
      - libgd2-noxpm-dev # Required for gnuplot png terminal
      
language: perl

env:
  gp_version=5.0.1
  
perl:
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

matrix:
  include:
    - perl: 5.24
      env: gp_version=5.0.5

before_install:
  # Prevent "Please tell me who you are" errors for certain DZIL configs
  - git config --global user.name "TravisCI"

install:
  # Install gnuplot 5 for plot tests. (Not available on Ubuntu 12.04)
  - cd /tmp
  - wget https://sourceforge.net/projects/gnuplot/files/gnuplot/$gp_version/gnuplot-$gp_version.tar.gz
  - tar -xf gnuplot-$gp_version.tar.gz
  - cd gnuplot-$gp_version
  - ./configure --prefix=$HOME/local
  - make -j2
  - make install
  - export PATH="$HOME/local/bin:$PATH"
  - gnuplot --version

  # Install the DZIL dependencies
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla

  # Install DZIL plugins etc if needed
  - cd $TRAVIS_BUILD_DIR
  - dzil authordeps --missing | grep -vP '[^\w:]' | xargs cpanm --quiet --notest

  # install dependencies
  - dzil listdeps --missing --cpanm | grep -vP '[^\w:~"\.]' | xargs cpanm --quiet --notest
  - cpanm -v -f PDL::Graphics::Gnuplot
  - cpanm -n Test::Perl::Critic

script:
  # "normal" tests
  - prove --verbose -l -s -r t
  
  # Perl::Critic tests
  - prove --verbose -l -r xt/critic/

  # Pod manual test
  - perl xt/pod-manual-coverage.pl
  
notifications:
  email: false
  irc: 
    channels: "chat.freenode.net#labmeasurement"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
