install:
  - choco install --allowemptychecksum --x86 strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  - cd Measurement
  - cpan App::cpanminus
  - cpanm --installdeps -n -v .

build_script:
  - perl ./Build.PL
  - ./Build
  - prove -v -b -r t
  