environment:
  matrix:
    # Cannot run dependency tests as the Test::TCP tests fails on windows:
    # https://github.com/tokuhirom/Test-TCP/issues/43 
    - strawberry_version: 5.20.1.1
      installdeps_options: -n -v
    - strawberry_version: 5.20.1.1 --x86
      installdeps_options: -n -v
      
install:
  - choco install --allowemptychecksum strawberryperl --version %strawberry_version%
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - choco install gnuplot
  - path C:\Program Files\gnuplot\bin;%PATH%
  - perl -V
  - cd Measurement
  - cpan App::cpanminus
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - dzil authordeps --missing | cpanm %installdeps_options%
  - dzil listdeps --missing | cpanm %installdeps_options%
  - cpanm -v -f PDL::Graphics::Gnuplot
  - cpanm -n Test::Perl::Critic

build_script:
  - prove --verbose -l -s -r t
  - prove --verbose -l -r xt\critic\
