environment:
  matrix:
    # Should we run dependency tests?
    - strawberry_version: 5.20.3.3
      installdeps_options: --verbose --notest
    - strawberry_version: 5.20.3.3 --x86
      installdeps_options: --verbose --notest
      
install:
  - choco install --allowemptychecksum strawberryperl --version %strawberry_version%
  - path C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\strawberry\c\bin;%PATH%
  # get gnuplot
  # - ps: Invoke-WebRequest https://sourceforge.net/projects/gnuplot/files/gnuplot/5.2.0/gp520-win64-mingw.exe/download -OutFile gp.exe -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
  - ps: Invoke-WebRequest https://github.com/lab-measurement/Lab-Measurement-Homepage/raw/master/gp524-win64-mingw_3.exe -OutFile gp.exe
  - start /wait gp.exe /VERYSILENT /SUPPRESSMSGBOXES
  - path "C:\Program Files\gnuplot\bin";%PATH% 
  - perl -V
  - gnuplot --version
  - cpanm %installdeps_options% --skip-satisfied Dist::Zilla
  - dzil authordeps --missing | cpanm %installdeps_options%
  - dzil listdeps --missing | cpanm %installdeps_options%
  - cpanm %installdeps_options% PDL::Graphics::Gnuplot
build_script:
  - prove --verbose -l -s -r t
