---
abstract: 'Connection modules for Lab::Measurement'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Connection
provides:
  Lab::Connection:
    file: lib/Lab/Connection.pm
    version: 1.0793
  Lab::Connection::DEBUG:
    file: lib/Lab/Connection/DEBUG.pm
  Lab::Connection::GPIB:
    file: lib/Lab/Connection/GPIB.pm
  Lab::Connection::MODBUS_RS232:
    file: lib/Lab/Connection/MODBUS_RS232.pm
  Lab::Connection::VISA:
    file: lib/Lab/Connection/VISA.pm
  Lab::Connection::VISA_GPIB:
    file: lib/Lab/Connection/VISA_GPIB.pm
  Lab::Connection::LinuxGPIB:
    file: lib/Lab/Connection/LinuxGPIB.pm
requires:
  Lab::Exception: 0.1
  Lab::Bus: 0.1
  Lab::VISA: 0.1
  Time::HiRes: 0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Connection
  homepage: http://labvisa.de
  license: http://dev.perl.org/licenses/
version: 0.5
