---
abstract: 'Exception handling for Lab::Instrument'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Exception
provides:
  Lab::Exception:
    file: lib/Lab/Exception.pm
    version: 2.90
  Lab::Exception::Base:
    file: lib/Lab/Exception.pm
requires:
  Exception::Class: 1.0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Exception
  homepage: http://labvisa.de
  license: http://dev.perl.org/licenses/
version: 2.90
