---
abstract: 'Instrument and bus drivers for Lab::Measurement'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Instrument
provides:
  Lab::Bus:
    file: lib/Lab/Bus.pm
    version: 2.90
  Lab::Bus::DEBUG:
    file: lib/Lab/Bus/DEBUG.pm
  Lab::Bus::DEBUG::HumanInstrument:
    file: lib/Lab/Bus/DEBUG.pm
  Lab::Bus::LinuxGPIB:
    file: lib/Lab/Bus/LinuxGPIB.pm
  Lab::Bus::MODBUS_RS232:
    file: lib/Lab/Bus/MODBUS_RS232.pm
  Lab::Bus::RS232:
    file: lib/Lab/Bus/RS232.pm
  Lab::Bus::VISA:
    file: lib/Lab/Bus/VISA.pm
  Lab::Connection:
    file: lib/Lab/Connection.pm
    version: 2.90
  Lab::Connection::DEBUG:
    file: lib/Lab/Connection/DEBUG.pm
  Lab::Connection::GPIB:
    file: lib/Lab/Connection/GPIB.pm
  Lab::Connection::LinuxGPIB:
    file: lib/Lab/Connection/LinuxGPIB.pm
  Lab::Connection::MODBUS_RS232:
    file: lib/Lab/Connection/MODBUS_RS232.pm
  Lab::Connection::VISA:
    file: lib/Lab/Connection/VISA.pm
  Lab::Connection::VISA_GPIB:
    file: lib/Lab/Connection/VISA_GPIB.pm
  Lab::Exception:
    file: lib/Lab/Exception.pm
    version: 2.90
  Lab::Exception::Base:
    file: lib/Lab/Exception.pm
  Lab::Instrument:
    file: lib/Lab/Instrument.pm
    version: 2.90
  Lab::Instrument::HP34401A:
    file: lib/Lab/Instrument/HP34401A.pm
  Lab::Instrument::SCPI::Agilent33220A:
    file: lib/Lab/Instrument/SCPI/Agilent33220A.pm
    version: 1.0000
  Lab::Instrument::SCPI::AgilentMSO:
    file: lib/Lab/Instrument/SCPI/AgilentMSO.pm
    version: 1.0000
  Lab::Instrument::SR830:
    file: lib/Lab/Instrument/SR830.pm
  Lab::Instrument::Source:
    file: lib/Lab/Instrument/Source.pm
  Lab::Instrument::TemperatureControl::TLK43:
    file: lib/Lab/Instrument/TemperatureControl/TLK43.pm
    version: 0.0720
  Lab::Instrument::Yokogawa7651:
    file: lib/Lab/Instrument/Yokogawa7651.pm
  Lab::Instrument::YokogawaGS200:
    file: lib/Lab/Instrument/YokogawaGS200.pm
requires:
  Exception::Class: 1.0
  Time::HiRes: 0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Instrument
  homepage: http://www.labmeasurement.de/
  license: http://dev.perl.org/licenses/
version: 2.90
