---
abstract: 'Instrument drivers for Lab::Measurement'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Instrument
provides:
  Lab::Instrument:
    file: lib/Lab/Instrument.pm
    version: 0.9
  Lab::Instrument::HP34401A:
    file: lib/Lab/Instrument/HP34401A.pm
    version: 0.95
  Lab::Instrument::SCPI::Agilent33220A:
    file: lib/Lab/Instrument/SCPI/Agilent33220A.pm
    version: 0.1
  Lab::Instrument::SCPI::AgilentMSO:
    file: lib/Lab/Instrument/SCPI/AgilentMSO.pm
    version: 0.1
  Lab::Instrument::SR830:
    file: lib/Lab/Instrument/SR830.pm
    version: 0.4
  Lab::Instrument::Source:
    file: lib/Lab/Instrument/Source.pm
    version: 0.9
  Lab::Instrument::Source::Yokogawa7651:
    file: lib/Lab/Instrument/Yokogawa7651.pm
    version: 0.9
  Lab::Instrument::Source::YokogawaGS200:
    file: lib/Lab/Instrument/YokogawaGS200.pm
    version: 0.2
  Lab::Instrument::TLK43:
    file: lib/Lab/Instrument/TemperatureControl/TLK43.pm
    version: 0.2
requires:
  Lab::Bus: 0.3
  Lab::Connection: 0.3
  Lab::Exception: 0.3
  Time::HiRes: 0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Instrument
  homepage: http://labvisa.de
  license: http://dev.perl.org/licenses/
version: 0.5
