---
abstract: 'Interface drivers for Lab::Instrument'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Connector
provides:
  Lab::Connector:
    file: lib/Lab/Connector.pm
    version: 1.0793
  Lab::Connector::DEBUG:
    file: lib/Lab/Connector/DEBUG.pm
  Lab::Connector::DEBUG::HumanInstrument:
    file: lib/Lab/Connector/DEBUG.pm
  Lab::Connector::GPIB:
    file: lib/Lab/Connector/GPIB.pm
  Lab::Connector::MODBUS_RS232:
    file: lib/Lab/Connector/MODBUS_RS232.pm
  Lab::Connector::RS232:
    file: lib/Lab/Connector/RS232.pm
    version: 1.0757
  Lab::Connector::VISA:
    file: lib/Lab/Connector/VISA.pm
requires:
  Lab::Exception: 0.1
  Lab::VISA: 0.1
  Time::HiRes: 0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Connector
  homepage: http://labvisa.de
  license: http://dev.perl.org/licenses/
version: 0.9
